version: "3.9"
services:
  web:
    build:
      context: app/
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./app/alembic:/alembic
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  test:
    profiles: ["test"]
    build:
      context: app/
      target: test
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///./test.db

volumes:
  db_data:
