version: "3.7"
services:
  web:
    build:
      context: app/
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./app/alembic:/alembic
      - ./app/logs:/logs
    env_file:
      - .env
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  test:
    build:
      context: app/
      target: test
    env_file:
      - .env
    environment:
      - DATABASE_URL=sqlite:///./test.db

  telegram_bot:
    build: bot/
    env_file:
      - .env
    environment:
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
      - NUMBER_OF_USERS=${NUMBER_OF_USERS}
      - MAX_LIKE_PER_USER=${MAX_LIKE_PER_USER}
      - MAX_POSTS_PER_USER=${MAX_POSTS_PER_USER}
      - WEB_APP_URL=http://web:8000
    depends_on:
      - web

volumes:
  db_data: